### ISSUE TITLE
[已解决][垂直方向] 如何定位到最后一个元素， 不抖动

### ISSUE THREAD

**Issue by 9a6c** [aillieo/UnityDynamicScrollView#10]
添加一个元素后，延迟一帧调用scrollView.ScrollTo(list.Count - 1)，会有明显的抖动

有什么方式，在添加元素后，定位到底部不抖动。
当前使用
    public void AddTalk(string context, bool isMy, int line = 1)
    {
        list.Add(new MARKET_TalkItem(context, isMy, line));

        scrollView.UpdateData(false);
        //延迟执行，到尾部（抖动）
        //StartCoroutine(DelayScrollToEnd());
    }

**Comment by aillieo** [comment]
已修复问题并提交到master 请更新

**Comment by 9a6c** [comment]
感谢您的维护，当前问题已解决
