### ISSUE TITLE
Error? Bug? List is suddently Empty

### ISSUE THREAD

**Issue by LordHelmchen12** [aillieo/UnityDynamicScrollView#7]
Hey, first of all - awesome list tool.
This boosted our performance by +50% :)

But i have some weird behaviour:

1. When I click grab the list and  move it Up and down very fast at somepoint list gets empty.
- ![grafik](https://user-images.githubusercontent.com/2505595/118498159-04acb600-b726-11eb-8a72-45503d31b92a.png)
- List has 3800 Entries
- List is for mobile so click and swipe is the way to use it in app

2. List is not scrolling to the end
I designed a letter scrollbar. So when i click on the letter "W" list jumps to a separator.
But for some reason when i press on "Z" ... list ends at the "W" Entries.
It wont let me scroll down any further.

Do you have any ideas whats hapening here?
Pls help I am lost :(

**Comment by LordHelmchen12** [comment]
I also recognized, when I use "ScrollTo(Index)" list often does not use pages anymore. I can scroll up and down a bit, but its not loading new entries above and below.

**Comment by LordHelmchen12** [comment]
After fiddeling around with your code i recognized It seemst to happen when the page list is changing size?
It does not like when I move up and down at the upper or lower edges of content page list.

This is how i figured that out!
![grafik](https://user-images.githubusercontent.com/2505595/118633687-0633b800-b7d2-11eb-86ea-47c51698cb70.png)
ScrollViewEx.cs lines: 113 - 132

Looking in scene showed me that content rect was swithing between no space above top item to pagesize.

**Comment by aillieo** [comment]
@LordHelmchen12 
Thanks for your support!
For issue 1:
Sorry for the trouble it is a bug indeed, and it has been fixed so just pull and update.
For issue 2:
This Component does not support scrollbar well for the time being. This is due to the performance consideration that the correct display of scrollbar needs to calculate the position and size of all entries first, and this process will be very time consuming and may cause lag.

**Comment by LordHelmchen12** [comment]
Hey thanks for youre response!
Issue 2 i fixed, was something wrong with my datalist so soooorry ^^ never mind this one.

For issue 1:
Can you tell me what or where you changed something? :-)


And for your scrollbar problem some feedback:
Since ScrollViewEx is for large lists, I gues nobody would care if you ignore size of elements and simply show CurrentIndex of AllIndex ratio with it :-)

Keep up the good work!

**Comment by aillieo** [comment]
@LordHelmchen12 
Sorry for the late response.

Glad to know that all your problems are resolved.

For issue 1:
What I missed is: when the distance 'Content' moved in one frame (dragging or inertia) exceeds the height of the 'Viewport', all the entries may disappear, so I added some extra condition checkings when calculating the visibility of entries and updating critical item index.

Thanks for the idea about the scrollbar it is great and I think it will added someday later.

Good luck and happy coding!
